### ISSUE TITLE
Missing example how SDK allows to access Vehicle Model branches 

### ISSUE THREAD

**Issue by DocMoebiuz** [eclipse-velocitas/velocitas-docs#17]
Missing examples how SDK allows to access NamedRange & Dictionary branches.

Currently only an implicit example for Vehicle Model access using NamedRanges is provided in the SDK Documentation.
An example for Dictionary-type branches is completely missing in the documentation.

## Expected Behavior
The SDK documentation in Velocitas Documentation contains an example for NamedRange and Dictionary. 

## Current Behavior
The SDK documentation in Velocitas Documentation contains an example for NamedRange (implicitly here: https://eclipse-velocitas.github.io/velocitas-docs/docs/concepts/python_vehicle_app_sdk/#subscribe-and-unsubscribe-to-a-single-datapoint). 
Dictionary is completely missing. 

## Possible Solution
Add explicit examples for access of NamedRanges and Dictionary-type branches in https://eclipse-velocitas.github.io/velocitas-docs/docs/concepts/python_vehicle_app_sdk/#subscribe-and-unsubscribe-to-a-single-datapoint.

## Steps to Reproduce
1. Go to SDK docs in Eclipse Velocitas Docs https://eclipse-velocitas.github.io/velocitas-docs/docs/concepts/python_vehicle_app_sdk/#subscribe-and-unsubscribe-to-a-single-datapoint
2. Try to find example for NamedRange and Dictionary-type branches

## Context (Environment)
While onboarding to the SDK this is a recurring question by developers.

**Comment by doosuu** [comment]
Hi @DocMoebiuz since this is quite old, is this still valid? Since we overhauled the NamedRange and Dictionary access completely. Can you shed some light on this? Thanks!
