### ISSUE TITLE
Website fails to load

### ISSUE THREAD

**Issue by sophokles73** [eclipse-velocitas/velocitas-docs#44]
When I try to open https://websites.eclipseprojects.io/velocitas/docs/about/development_model/ in my (latest) Firefox browser, the page fails to load. The browser's developer console indicates several issues with loading required resources. See screenshot ...

![image](https://user-images.githubusercontent.com/5682135/193996145-1baca77c-9f16-4910-b382-4824bda9906e.png)

This is the same page in a recent version of Chromium ...

![image](https://user-images.githubusercontent.com/5682135/193996461-c953802c-e3c4-4ecc-84cd-7d4750655c67.png)

**Comment by gkreyssing** [comment]
Thanks for pointing out this issue. We will check it.

**Comment by DocMoebiuz** [comment]
Problem is that the base path is not used correctly for locally hosted js and fonts.

**Comment by gkreyssing** [comment]
@DocMoebiuz Looks much better but still one error:
![image](https://user-images.githubusercontent.com/12787112/194231644-45f91973-8391-4824-8f46-5dfd06120c9f.png)
