### ISSUE TITLE
The Working behind a Proxy guide seems to be outdated

### ISSUE THREAD

**Issue by sophokles73** [eclipse-velocitas/velocitas-docs#46]
The instructions provided in https://websites.eclipseprojects.io/velocitas/docs/tutorials/quickstart/behind_proxy/ do not seem to reflect the current implementation. The [Visual Studio Code](https://websites.eclipseprojects.io/velocitas/docs/tutorials/quickstart/behind_proxy/#visual-studio-code) section refers to the `.devcontainer/Dockerfile.Proxy` file which does not seem to exist in the Vehicle App repository.

I also wonder if Docker Desktop is really a requirement for using Velocitas, given that Docker Desktop is not necessarily free-to-use in a corporate environment.

**Comment by clemensfreitagbosch** [comment]
Maybe we should add at least a hint that another option for Windows users would be run Docker in WSL2, like I personally do. 
The question on how to correctly configure the proxy inside WSL2 isn't any different, but it's not bound to Docker Desktop.

**Comment by MP91** [comment]
fixed by #64
