### ISSUE TITLE
Klicking on the "tutorial" Link within chapter "vehicle app deployment with helm" leads to a 404

### ISSUE THREAD

**Issue by ansgarl** [eclipse-velocitas/velocitas-docs#55]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior
chapter with more details on how to setup K3D opens in browser

## Current Behavior
klicking on the link leads to a 404 error

## Possible Solution
fix the link

## Steps to Reproduce

1.open (https://websites.eclipseprojects.io/velocitas/docs/tutorials/tutorial_how_to_deploy_a_vehicle_app_with_helm/)
2.click on the "tutorial" link
3. link refers to "https://websites.eclipseprojects.io/velocitas/run_runtime_services_kubernetes.md" which seem to don't exist since it leads into a 404

## Context (Environment)
Velocitas Docu on webpage

## Possible Implementation
fix the link to the proper one

**Comment by gkreyssing** [comment]
Broken linked solved. Thanks for reporting.

**Comment by gkreyssing** [comment]
Just realized that you mentioned another broker link on the page.
