### ISSUE TITLE
Quickstart: Unclear note on Dapr extension reload

### ISSUE THREAD

**Issue by clemensfreitagbosch** [eclipse-velocitas/velocitas-docs#67]
I started with a 

* Already working DevContainer setup with VS Code 1.69.1 and Docker on WSL2
* Fresh generation from the [eclipse-velocitas/vehicle-app-python-template](https://github.com/eclipse-velocitas/vehicle-app-python-template)
* Following the Quickstart Guide

In general, it was very easy to follow the Guide, thumbs up for that 👍 

The only point I stumbled upon was the note on 

_When opening the devContainer for the first time, a manual reload of the dapr extension is required, if the extension hasn´t been _installed before. The reload button appears next to Dapr extension in extension menue.__

Where should I do this, and is it even necessary?

When I first opened the Dapr extension, it told me that no compatible Dapr version is running right now (probably expected). 
However I didn't found any "reload button". Reloading an extension in general seems to be done by reloading the window (https://github.com/Microsoft/vscode/issues/31712), which didn't seem to change something. 

However, after running the `Start Vehicle App runtime` I'm up and running anyway. 

Not a big deal in general, but actually while following the whole Quickstart Guide this was the only confusing part for me 😄

**Comment by gkreyssing** [comment]
Hey Clemens, thanks for you feedback. 
We will check how we can improve the Quick Start Guide and come back to you soon.
