### ISSUE TITLE
Broken link in Python Vehicle App Development Run App section

### ISSUE THREAD

**Issue by lukasmittag** [eclipse-velocitas/velocitas-docs#70]
## Expected Behavior
https://websites.eclipseprojects.io/velocitas/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_python/ Link should work

## Current Behavior
Not Found

The requested URL /velocitas/docs/tutorials/vehicle-app-runtime/run_runtime_services_locally.md was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

## Steps to Reproduce
1. Click on the second link in this section: 'Run your App
In order to run the app make sure you have the seatservice configured as a dependency in your [./AppManifest.json](https://github.com/eclipse-velocitas/vehicle-app-python-template/blob/main/AppManifest.json). Read more about it in the [run runtime services](https://websites.eclipseprojects.io/velocitas/docs/tutorials/vehicle-app-runtime/run_runtime_services_locally.md) section.'

I guess it should link to this: https://websites.eclipseprojects.io/velocitas/docs/tutorials/vehicle-app-runtime/run_runtime_services_locally/

**Comment by dennismeister93** [comment]
Thanks for notifying us @lukasmittag :)
We are currently working on our documentation - fix is coming soon!

**Comment by dennismeister93** [comment]
Fixed within https://github.com/eclipse-velocitas/velocitas-docs/pull/76
