### ISSUE TITLE
Search function on https://websites.eclipseprojects.io/velocitas/ not working

### ISSUE THREAD

**Issue by BjoernAtBosch** [eclipse-velocitas/velocitas-docs#75]
Search function on https://websites.eclipseprojects.io/velocitas/ (upper right corner: "Search this site...") is not working.

## Expected Behavior
Search should offer results or message about no results found

## Current Behavior
After entering some text and hitting enter key nothing happens

## Possible Solution
-/-

## Steps to Reproduce
1. Open https://websites.eclipseprojects.io/velocitas/
2. Klick on the search field
3. Enter some text
4. Hit enter key
--> Nothing happens

## Context (Environment)
Browser: Firefox 102.7.0esr (64-Bit)
Same for: Google Chrom Version 109.0.5414.120 (Official Build) (64-bit)
Same for: Microsoft Edge Version 109.0.1518.70 (Official build) (64-bit)
OS: Windows 10

## Possible Implementation
Remove search field if no fast fix is possible

**Comment by dennismeister93** [comment]
Fixed with https://github.com/eclipse-velocitas/velocitas-docs/pull/78
