### ISSUE TITLE
Eclipse Velocitas Release Strategy Proposal

### ISSUE THREAD

**Issue by kse3hi** [eclipse-velocitas/velocitas-docs#88]
### Motivation:
As developers/users of Eclipse Velocitas, we would like to have clear vision of release strategy, with clear overview of released components (incl. their versions). 
It will be great to have **stable** and **baselined** state of template and major components to be able  to keep stable environment especially in dynamical development phase.

### Versioning Principle

**_Major_** releases include API changes (potential for downstream breakage);
**_Minor_** releases add new functionality, but are API compatible with previous versions; and
**_Service_** releases include bug fixes only and include no significant new functionality.

_Versioning scheme:_ `<major>.<minor>.<service>`
_Example:_ `0.1.0`

### Release Strategy Proposal:
![image](https://user-images.githubusercontent.com/97447206/229811735-b29fd5b5-4410-42f0-88d7-e80f55d79b11.png)

**Comment by kse3hi** [comment]
Communication threat on GitHub about template versioning, that can help us with our Versioning Strategy: https://github.com/orgs/community/discussions/45248

**Comment by gkreyssing** [comment]
@kse3hi As we release velocitas, I would close this issue. Do you agree?

**Comment by kse3hi** [comment]
@gkreyssing , release concept was accepted and implemented.
