### ISSUE TITLE
Link to Contribution Guideline is not working

### ISSUE THREAD

**Issue by eriksven** [eclipse-velocitas/velocitas-docs#94]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior

When on the site https://eclipse-velocitas.github.io/velocitas-docs/community/, and selecting the link to "Contribution Guideline", I am forwarded to the website describing the contribution guideline and how to contribute to Eclipse Velocitas. 
## Current Behavior

There is an error message indicating: "404 There isn't a GitHub Pages site here." . The referenced page is https://eclipse-velocitas.github.io/docs/contribution-guidelines/. 
## Possible Solution

Fix the link or make sure that the Contribution Guideline is online available under that link. I am not sure where the guideline should be at the moment. 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by eriksven** [comment]
Thanks for the quick fix. So far the 404 message remains for me. Let's see when it will be reflected in the documentation.

**Comment by dennismeister93** [comment]
@eriksven I have an eye on that - i will update you when new version is deployed :)

**Comment by dennismeister93** [comment]
Sorry for delay, forgot to tell you that the link is working now @eriksven

**Comment by eriksven** [comment]
@dennismeister93, thank you for the update. Unfortunately, for me it does not work from this side: https://eclipse-velocitas.github.io/velocitas-docs/community/ and results in a 404 message from GitHub.

**Comment by eriksven** [comment]
The seems to work now.

**Comment by dennismeister93** [comment]
Great! Finally :)
